spring.application.name=F3M
spring.datasource.url=jdbc:postgresql://localhost:5432/FarmerToMarket
spring.datasource.username=postgres
spring.datasource.password=151042
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.servlet.session.cookie.same-site=lax
spring.security.oauth2.client.registration.google.client-id=759680035640-ovkvtt5bafcuopqmn6mj1smpmc1asur1.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile

spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

spring.security.oauth2.client.registration.google.client-name=Google
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=10MB
server.tomcat.max-part-count=10000
spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=2KB
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisDialect
